### ISSUE TITLE
elm-oracle suggestions don't  work on Windows 7

### ISSUE THREAD

**Issue by hipertracker** [edubkendo/atom-elm#36]
I have installed a fresh Atom 1.5.3 under Windows 7 Enterprise SP1. I did all as described at https://github.com/edubkendo/atom-elm. I added ```language-elm``` package through the editor. I also installed ```elm-oracle``` as global npm package. 

For Windows ```where elm-oracle``` command returns two paths, one is pointing to ```elm-oracle```, the second is pointing to ```elm-oracle.cmd```. I tried both. None is working. When I try to get autocompletion I always get the same error:

```
Uncaught Error: No elm-oracle suggestions
/C:/Users/hipertracker/.atom/packages/language-elm/lib/elmOracle.js:144

Error: No elm-oracle suggestions
    at parseOutput (C:/Users/hipertracker/.atom/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions (C:/Users/hipertracker/.atom/packages/language-elm/lib/elmOracle.js:27:27)
    at ChildProcess.<anonymous> (C:/Users/hipertracker/.atom/packages/language-elm/lib/elmOracle.js:62:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

The funny part is it works on OS X and on Windows 10. I have that problem only on Windows 7.

**Comment by hipertracker** [comment]
I compared  not working autocompletion settings on Windows 7  with Windows 10. There is no need to install ```elm-oracle``` as global Npm package because Atom's package _have it installed already_ internally. I don't have any ```elm-oracle``` installed from Npm on Windows 10 and all works. 

There is a slight difference is path between Windows 7 and Windows 10. Windows 7 uses ```..../bin/elm-oracle` (bin without dot) and Windows 10 and OS X use ```..../.bin/elm-oracle``` (bin with dot in name). But even if I point to that internal ```elm-oracle``` installed by ```language-elm```, I still get the same exception in Atom under Windows 7.  So, whatever I do, it still does not work. Windows 10 and OS X is fine.

**Comment by brianegan** [comment]
Thanks! I should update the instructions to say it's optional to install elm-oracle (if you wanted to use a specific version, for example).

I'll try to take a look at this, but don't have a windows machine, so it's pretty hard to debug from my side. Anyone else with Windows 7 machines that's willing to help out?

**Comment by brianegan** [comment]
And just to double-check: you've run `elm package install` in the project folder as well, correct?

**Comment by brianegan** [comment]
Hey there! Got a bit of time to look into this today. Installed Win7 via VirtualBox, not a ton of fun, but ran into the same issue. What I found out: Node wasn't working properly. Could you try following this answer:

http://stackoverflow.com/questions/23412938/node-is-not-recognized-as-an-internal-or-an-external-command-operable-program?answertab=votes#tab-top

And see if it fixes the problem for you as well? What happened for me is that node wasn't able to run properly because I didn't have it configured int my User variables PATH environment variable. Please try adding it to that environment variable following the instructions in the link and let me know if that works!

Sorry about the trouble, and thanks for bringing this up so we can get it fixed :)

**Comment by brianegan** [comment]
Hey there @hipertracker -- did you get a chance to try following those instructions to see if it fixes the problem?

**Comment by jovaneyck** [comment]
I have a work PC running Windows 7 (I know) and encountered this exact same problem. Node was already in my PATH so I decided to do some digging. I LOVE how Atom is just Javascript :smile: 

Anyways, for me the problem was I had a .cmd file that executed everytime I open a command line (similar to a .bashrc file).

The elmOracle.js file contains the following snippet:

`const provideSuggestions = () => {
      resolve(JSON.parse((parseOutput(lines[0]))))
    }
`
which seems to trap console output from something. However, as my bootstrap .cmd file echoed some stuff to console it took that instead. Changing it to the following fixes my problem:

`const provideSuggestions = () => {
      resolve(JSON.parse((parseOutput(lines[lines.length - 1]))))
    }
`

Can anyone point me to how that accumulateOutput works/is supposed to work? I feel uncomfortable PR'ing something I know nothing about
